In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, f1_score, recall_score, confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [18]:
df = pd.read_csv("Churn_treino.csv", sep=';')
df

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0             619    France  Female   42       2         0              1   
1             608     Spain  Female   41       1   8380786              1   
2             502    France  Female   42       8   1596608              3   
3             699    France  Female   39       1         0              2   
4             850     Spain  Female   43       2  12551082              1   
...           ...       ...     ...  ...     ...       ...            ...   
9995          771    France    Male   39       5         0              2   
9996          516    France    Male   35      10   5736961              1   
9997          709    France  Female   36       7         0              1   
9998          772   Germany    Male   42       3   7507531              2   
9999          792    France  Female   28       4  13014279              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1         10134888       1  
1             0               1         11254258       0  
2             1               0         11393157       1  
3             0               0          9382663       0  
4             1               1           790841       0  
...         ...             ...              ...     ...  
9995          1               0          9627064       0  
9996          1               1         10169977       0  
9997          0               1          4208558       1  
9998          1               0          9288852       1  
9999          1               0          3819078       0  

[10000 rows x 11 columns]

In [19]:
X = df.drop('Exited', axis=1)
y = df['Exited']
X

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0             619    France  Female   42       2         0              1   
1             608     Spain  Female   41       1   8380786              1   
2             502    France  Female   42       8   1596608              3   
3             699    France  Female   39       1         0              2   
4             850     Spain  Female   43       2  12551082              1   
...           ...       ...     ...  ...     ...       ...            ...   
9995          771    France    Male   39       5         0              2   
9996          516    France    Male   35      10   5736961              1   
9997          709    France  Female   36       7         0              1   
9998          772   Germany    Male   42       3   7507531              2   
9999          792    France  Female   28       4  13014279              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1         10134888  
1             0               1         11254258  
2             1               0         11393157  
3             0               0          9382663  
4             1               1           790841  
...         ...             ...              ...  
9995          1               0          9627064  
9996          1               1         10169977  
9997          0               1          4208558  
9998          1               0          9288852  
9999          1               0          3819078  

[10000 rows x 10 columns]

In [20]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [21]:
std_scl = StandardScaler()
numerical = X.select_dtypes(include=['int64', 'float64']).columns
X[numerical] = std_scl.fit_transform(X[numerical])
X

CreditScore Geography  Gender       Age    Tenure   Balance  \
0       -0.326221    France  Female  0.293517 -1.041760 -1.110553   
1       -0.440036     Spain  Female  0.198164 -1.387538  0.222782   
2       -1.536794    France  Female  0.293517  1.032908 -0.856542   
3        0.501521    France  Female  0.007457 -1.387538 -1.110553   
4        2.063884     Spain  Female  0.388871 -1.041760  0.886252   
...           ...       ...     ...       ...       ...       ...   
9995     1.246488    France    Male  0.007457 -0.004426 -1.110553   
9996    -1.391939    France    Male -0.373958  1.724464 -0.197835   
9997     0.604988    France  Female -0.278604  0.687130 -1.110553   
9998     1.256835   Germany    Male  0.293517 -0.695982  0.083852   
9999     1.463771    France  Female -1.041433 -0.350204  0.959944   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0         -0.911583   0.646092        0.970243         0.170614  
1         -0.911583  -1.547768        0.970243         0.353281  
2          2.527057   0.646092       -1.030670         0.375948  
3          0.807737  -1.547768       -1.030670         0.047859  
4         -0.911583   0.646092        0.970243        -1.354223  
...             ...        ...             ...              ...  
9995       0.807737   0.646092       -1.030670         0.087743  
9996      -0.911583   0.646092        0.970243         0.176340  
9997      -0.911583  -1.547768        0.970243        -0.796492  
9998       0.807737   0.646092       -1.030670         0.032551  
9999      -0.911583   0.646092       -1.030670        -0.860051  

[10000 rows x 10 columns]

In [22]:
lbl_enc = LabelEncoder()
categorical = X.select_dtypes(include='object').columns
for col in categorical:
    X[col] = lbl_enc.fit_transform(X[col])
X

CreditScore  Geography  Gender       Age    Tenure   Balance  \
0       -0.326221          0       0  0.293517 -1.041760 -1.110553   
1       -0.440036          2       0  0.198164 -1.387538  0.222782   
2       -1.536794          0       0  0.293517  1.032908 -0.856542   
3        0.501521          0       0  0.007457 -1.387538 -1.110553   
4        2.063884          2       0  0.388871 -1.041760  0.886252   
...           ...        ...     ...       ...       ...       ...   
9995     1.246488          0       1  0.007457 -0.004426 -1.110553   
9996    -1.391939          0       1 -0.373958  1.724464 -0.197835   
9997     0.604988          0       0 -0.278604  0.687130 -1.110553   
9998     1.256835          1       1  0.293517 -0.695982  0.083852   
9999     1.463771          0       0 -1.041433 -0.350204  0.959944   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0         -0.911583   0.646092        0.970243         0.170614  
1         -0.911583  -1.547768        0.970243         0.353281  
2          2.527057   0.646092       -1.030670         0.375948  
3          0.807737  -1.547768       -1.030670         0.047859  
4         -0.911583   0.646092        0.970243        -1.354223  
...             ...        ...             ...              ...  
9995       0.807737   0.646092       -1.030670         0.087743  
9996      -0.911583   0.646092        0.970243         0.176340  
9997      -0.911583  -1.547768        0.970243        -0.796492  
9998       0.807737   0.646092       -1.030670         0.032551  
9999      -0.911583   0.646092       -1.030670        -0.860051  

[10000 rows x 10 columns]

In [23]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.3, random_state=0)

### Montando a Rede Neural com Keras

In [24]:
model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=X_treino.shape[1]))
model.add(Dropout(0.4))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(units=1, activation='sigmoid'))

c:\Users\roger\OneDrive\Documentos\Coding\Machine-Learning-Testes\env\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_treino, y_treino, epochs=150, batch_size=32)

Epoch 1/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7870 - loss: 0.5173
Epoch 2/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7994 - loss: 0.4648
Epoch 3/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8027 - loss: 0.4494
Epoch 4/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8133 - loss: 0.4351
Epoch 5/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8226 - loss: 0.4181
Epoch 6/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8253 - loss: 0.4055
Epoch 7/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8289 - loss: 0.4025
Epoch 8/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8346 - loss: 0.3952
Epoch 9/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8360 - loss: 0.3923
Epoch 10/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8396 - loss: 0.3891
Epoch 11/150
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8419 - loss: 0.3841
Epoch 12/150
219/219 ━━━━━━━━━━━━━━━━━━━━

In [35]:
y_hat = model.predict(X_teste)
y_hat

94/94 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step


array([[0.32493594],
       [0.22174942],
       [0.13600321],
       ...,
       [0.0527525 ],
       [0.1062855 ],
       [0.62308437]], shape=(3000, 1), dtype=float32)

In [36]:
y_pred = (y_hat > 0.5).astype('int32')
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], shape=(3000, 1), dtype=int32)

In [39]:
print('acurácia:', accuracy_score(y_teste, y_pred))
print('F1:', f1_score(y_teste, y_pred))
print('recall:', recall_score(y_teste, y_pred))
print('Matriz de Confusão:\n', confusion_matrix(y_teste, y_pred))

acurácia: 0.8576666666666667
F1: 0.5898174831892411
recall: 0.4943639291465378
Matriz de Confusão:
 [[2266  113]
 [ 314  307]]
